### ISSUE TITLE
UI not showing

### ISSUE THREAD

**Issue by Sungjb** [lowag/libremaint#12]
Hey, im trying this out on cpanel, and i cannot manage to load the UI
<img width="942" alt="Screenshot 2024-06-23 at 19 39 55" src="https://github.com/lowag/libremaint/assets/173596303/7f192734-4d26-40e3-ba6a-65eb9e7d6f3b">

**Comment by lowag** [comment]
Please check the end of the "lm-debug.log" file you can find in the libremaint folder.

**Comment by Sungjb** [comment]
[24-Jun-2024 11:18:21 Asia/Jakarta] PHP Warning:  mysqli::__construct(): (HY000/1044): Access denied for user 'mylt3526_Admin'@'localhost' to database 'mylt3526' in /home/mylt3526/public_html/includes/MYSQL_db_class.php on line 34
[24-Jun-2024 11:21:17 Asia/Jakarta] PHP Warning:  mysqli::__construct(): (HY000/1044): Access denied for user 'mylt3526_Admin'@'localhost' to database 'mylt3526' in /home/mylt3526/public_html/includes/MYSQL_db_class.php on line 34

theres only that

**Comment by lowag** [comment]
Have you checked the 2nd point at the https://github.com/lowag/libremaint/blob/main/install.txt ?
The problem is that your webserver can't connect to your database.

**Comment by Sungjb** [comment]
Hey, i appreciate your help but i still cant manage to have the ui yet
<img width="434" alt="Screenshot 2024-06-24 at 13 06 48" src="https://github.com/lowag/libremaint/assets/173596303/f914f30e-8912-4d61-b863-b23701e2490d">

**Comment by lowag** [comment]
Isn't there any further warning at the of the  lm-debug.log ?  Please check it.

**Comment by Sungjb** [comment]
[24-Jun-2024 11:37:02 Asia/Jakarta] select * FROM users WHERE username='admin'
[24-Jun-2024 11:37:02 Asia/Jakarta] SELECT service_interval_date,service_interval_hours,repetitive,service_interval_mileage,workrequest_id, counter_id FROM workrequests WHERE repetitive>0 AND workrequest_status=3
[24-Jun-2024 11:37:02 Asia/Jakarta] SELECT Monday_start as start,Monday_end as end FROM users WHERE user_id=1
[24-Jun-2024 11:37:02 Asia/Jakarta] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(/home/mylt3526/public_html/libremaint-main/info_files/): failed to open dir: No such file or directory in /home/mylt3526/public_html/libremaint-main/pages/dashboard.php:104
Stack trace:
#0 /home/mylt3526/public_html/libremaint-main/pages/dashboard.php(104): FilesystemIterator->__construct('/home/mylt3526/...', 4096)
#1 /home/mylt3526/public_html/libremaint-main/pages/lm-body.php(51): require_once('/home/mylt3526/...')
#2 /home/mylt3526/public_html/libremaint-main/index.php(30): require('/home/mylt3526/...')
#3 {main}
  thrown in /home/mylt3526/public_html/libremaint-main/pages/dashboard.php on line 104
[24-Jun-2024 13:06:17 Asia/Jakarta] PHP Warning:  mysqli::__construct(): (HY000/1045): Access denied for user 'Admin'@'localhost' (using password: YES) in /home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php on line 34
[24-Jun-2024 13:19:39 Asia/Jakarta] PHP Parse error:  syntax error, unexpected end of file, expecting ';' in /home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php on line 125
[24-Jun-2024 13:20:08 Asia/Jakarta] PHP Parse error:  syntax error, unexpected end of file, expecting ';' in /home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php on line 125
[24-Jun-2024 13:20:41 Asia/Jakarta] PHP Warning:  require(/home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php): failed to open stream: No such file or directory in /home/mylt3526/public_html/libremaint-main/includes/lm-load.php on line 81
[24-Jun-2024 13:20:41 Asia/Jakarta] PHP Fatal error:  require(): Failed opening required '/home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/mylt3526/public_html/libremaint-main/includes/lm-load.php on line 81


here, thank you very much for helping me

**Comment by lowag** [comment]
There is something wrong with the /home/mylt3526/public_html/libremaint-main/includes/MYSQL_db_class.php file "unexpected end of file".  Please download and replace it.

**Comment by Sungjb** [comment]
replaced, the ui is still not loading
:l

**Comment by lowag** [comment]
tail of the lm-debug.log?

**Comment by Sungjb** [comment]
yup, nope still the same code 
<img width="674" alt="Screenshot 2024-06-24 at 13 56 19" src="https://github.com/lowag/libremaint/assets/173596303/3eb30dcd-dfb1-40a0-9843-9facfa8379be">


I'm doing your project on Cpanel btw

**Comment by lowag** [comment]
It must be something Cpanel specific. Please download again the MYSQL_db_class.php. I have changed that.

**Comment by Sungjb** [comment]
tried installing on ubuntu still no UI idk what did I do wrong, I did all the steps as taught

**Comment by lowag** [comment]
tail of the lm-debug.log?

**Comment by lowag** [comment]
In this case there is no warning and error. so it should be OK. If you use Firefox please try CTRL+SHIFT+i and reload the page.

**Comment by Sungjb** [comment]
<img width="541" alt="Screenshot 2024-06-25 at 08 27 24" src="https://github.com/lowag/libremaint/assets/173596303/53c9bd2f-e0d7-4a29-aa89-1a3199998180">


i got this issue from console what does it mean?

**Comment by lowag** [comment]
That means you you should set the correct IP address in libremaint/config/lm-config.php in line 5.
your_server_ip_or_name > e.g 127.0.0.1 (if your server on your localhost)

**Comment by Sungjb** [comment]
ohhh ic ic, Nice i worked it out. Thank you for helping me

can I get a guided for the telegram bot?
